// Generated by gencpp from file my_robot_tutorial/OddEvenCheck.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_TUTORIAL_MESSAGE_ODDEVENCHECK_H
#define MY_ROBOT_TUTORIAL_MESSAGE_ODDEVENCHECK_H

#include <ros/service_traits.h>


#include <my_robot_tutorial/OddEvenCheckRequest.h>
#include <my_robot_tutorial/OddEvenCheckResponse.h>


namespace my_robot_tutorial
{

struct OddEvenCheck
{

typedef OddEvenCheckRequest Request;
typedef OddEvenCheckResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OddEvenCheck
} // namespace my_robot_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_robot_tutorial::OddEvenCheck > {
  static const char* value()
  {
    return "4ff0b0ab1ed04611e3a2b4090af9ee4f";
  }

  static const char* value(const ::my_robot_tutorial::OddEvenCheck&) { return value(); }
};

template<>
struct DataType< ::my_robot_tutorial::OddEvenCheck > {
  static const char* value()
  {
    return "my_robot_tutorial/OddEvenCheck";
  }

  static const char* value(const ::my_robot_tutorial::OddEvenCheck&) { return value(); }
};


// service_traits::MD5Sum< ::my_robot_tutorial::OddEvenCheckRequest> should match
// service_traits::MD5Sum< ::my_robot_tutorial::OddEvenCheck >
template<>
struct MD5Sum< ::my_robot_tutorial::OddEvenCheckRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_tutorial::OddEvenCheck >::value();
  }
  static const char* value(const ::my_robot_tutorial::OddEvenCheckRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_tutorial::OddEvenCheckRequest> should match
// service_traits::DataType< ::my_robot_tutorial::OddEvenCheck >
template<>
struct DataType< ::my_robot_tutorial::OddEvenCheckRequest>
{
  static const char* value()
  {
    return DataType< ::my_robot_tutorial::OddEvenCheck >::value();
  }
  static const char* value(const ::my_robot_tutorial::OddEvenCheckRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_robot_tutorial::OddEvenCheckResponse> should match
// service_traits::MD5Sum< ::my_robot_tutorial::OddEvenCheck >
template<>
struct MD5Sum< ::my_robot_tutorial::OddEvenCheckResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_tutorial::OddEvenCheck >::value();
  }
  static const char* value(const ::my_robot_tutorial::OddEvenCheckResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_tutorial::OddEvenCheckResponse> should match
// service_traits::DataType< ::my_robot_tutorial::OddEvenCheck >
template<>
struct DataType< ::my_robot_tutorial::OddEvenCheckResponse>
{
  static const char* value()
  {
    return DataType< ::my_robot_tutorial::OddEvenCheck >::value();
  }
  static const char* value(const ::my_robot_tutorial::OddEvenCheckResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_ROBOT_TUTORIAL_MESSAGE_ODDEVENCHECK_H
