// Generated by gencpp from file project_1/TurnCameraRequest.msg
// DO NOT EDIT!


#ifndef PROJECT_1_MESSAGE_TURNCAMERAREQUEST_H
#define PROJECT_1_MESSAGE_TURNCAMERAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace project_1
{
template <class ContainerAllocator>
struct TurnCameraRequest_
{
  typedef TurnCameraRequest_<ContainerAllocator> Type;

  TurnCameraRequest_()
    : turn_degrees(0.0)  {
    }
  TurnCameraRequest_(const ContainerAllocator& _alloc)
    : turn_degrees(0.0)  {
  (void)_alloc;
    }



   typedef float _turn_degrees_type;
  _turn_degrees_type turn_degrees;





  typedef boost::shared_ptr< ::project_1::TurnCameraRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project_1::TurnCameraRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TurnCameraRequest_

typedef ::project_1::TurnCameraRequest_<std::allocator<void> > TurnCameraRequest;

typedef boost::shared_ptr< ::project_1::TurnCameraRequest > TurnCameraRequestPtr;
typedef boost::shared_ptr< ::project_1::TurnCameraRequest const> TurnCameraRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project_1::TurnCameraRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project_1::TurnCameraRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::project_1::TurnCameraRequest_<ContainerAllocator1> & lhs, const ::project_1::TurnCameraRequest_<ContainerAllocator2> & rhs)
{
  return lhs.turn_degrees == rhs.turn_degrees;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::project_1::TurnCameraRequest_<ContainerAllocator1> & lhs, const ::project_1::TurnCameraRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace project_1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::project_1::TurnCameraRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_1::TurnCameraRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project_1::TurnCameraRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project_1::TurnCameraRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_1::TurnCameraRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_1::TurnCameraRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project_1::TurnCameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "803e1cc74e9854b083917274010e0d5c";
  }

  static const char* value(const ::project_1::TurnCameraRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x803e1cc74e9854b0ULL;
  static const uint64_t static_value2 = 0x83917274010e0d5cULL;
};

template<class ContainerAllocator>
struct DataType< ::project_1::TurnCameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project_1/TurnCameraRequest";
  }

  static const char* value(const ::project_1::TurnCameraRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project_1::TurnCameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 turn_degrees\n"
;
  }

  static const char* value(const ::project_1::TurnCameraRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project_1::TurnCameraRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turn_degrees);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurnCameraRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project_1::TurnCameraRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project_1::TurnCameraRequest_<ContainerAllocator>& v)
  {
    s << indent << "turn_degrees: ";
    Printer<float>::stream(s, indent + "  ", v.turn_degrees);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT_1_MESSAGE_TURNCAMERAREQUEST_H
