// Generated by gencpp from file project_1/TurnCamera.msg
// DO NOT EDIT!


#ifndef PROJECT_1_MESSAGE_TURNCAMERA_H
#define PROJECT_1_MESSAGE_TURNCAMERA_H

#include <ros/service_traits.h>


#include <project_1/TurnCameraRequest.h>
#include <project_1/TurnCameraResponse.h>


namespace project_1
{

struct TurnCamera
{

typedef TurnCameraRequest Request;
typedef TurnCameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TurnCamera
} // namespace project_1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::project_1::TurnCamera > {
  static const char* value()
  {
    return "d2bd6d55eaa6b367037dff843fa7a83c";
  }

  static const char* value(const ::project_1::TurnCamera&) { return value(); }
};

template<>
struct DataType< ::project_1::TurnCamera > {
  static const char* value()
  {
    return "project_1/TurnCamera";
  }

  static const char* value(const ::project_1::TurnCamera&) { return value(); }
};


// service_traits::MD5Sum< ::project_1::TurnCameraRequest> should match
// service_traits::MD5Sum< ::project_1::TurnCamera >
template<>
struct MD5Sum< ::project_1::TurnCameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::project_1::TurnCamera >::value();
  }
  static const char* value(const ::project_1::TurnCameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::project_1::TurnCameraRequest> should match
// service_traits::DataType< ::project_1::TurnCamera >
template<>
struct DataType< ::project_1::TurnCameraRequest>
{
  static const char* value()
  {
    return DataType< ::project_1::TurnCamera >::value();
  }
  static const char* value(const ::project_1::TurnCameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::project_1::TurnCameraResponse> should match
// service_traits::MD5Sum< ::project_1::TurnCamera >
template<>
struct MD5Sum< ::project_1::TurnCameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::project_1::TurnCamera >::value();
  }
  static const char* value(const ::project_1::TurnCameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::project_1::TurnCameraResponse> should match
// service_traits::DataType< ::project_1::TurnCamera >
template<>
struct DataType< ::project_1::TurnCameraResponse>
{
  static const char* value()
  {
    return DataType< ::project_1::TurnCamera >::value();
  }
  static const char* value(const ::project_1::TurnCameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJECT_1_MESSAGE_TURNCAMERA_H
