// Generated by gencpp from file examples/OddEvenCheck.msg
// DO NOT EDIT!


#ifndef EXAMPLES_MESSAGE_ODDEVENCHECK_H
#define EXAMPLES_MESSAGE_ODDEVENCHECK_H

#include <ros/service_traits.h>


#include <examples/OddEvenCheckRequest.h>
#include <examples/OddEvenCheckResponse.h>


namespace examples
{

struct OddEvenCheck
{

typedef OddEvenCheckRequest Request;
typedef OddEvenCheckResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OddEvenCheck
} // namespace examples


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::examples::OddEvenCheck > {
  static const char* value()
  {
    return "4ff0b0ab1ed04611e3a2b4090af9ee4f";
  }

  static const char* value(const ::examples::OddEvenCheck&) { return value(); }
};

template<>
struct DataType< ::examples::OddEvenCheck > {
  static const char* value()
  {
    return "examples/OddEvenCheck";
  }

  static const char* value(const ::examples::OddEvenCheck&) { return value(); }
};


// service_traits::MD5Sum< ::examples::OddEvenCheckRequest> should match
// service_traits::MD5Sum< ::examples::OddEvenCheck >
template<>
struct MD5Sum< ::examples::OddEvenCheckRequest>
{
  static const char* value()
  {
    return MD5Sum< ::examples::OddEvenCheck >::value();
  }
  static const char* value(const ::examples::OddEvenCheckRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::examples::OddEvenCheckRequest> should match
// service_traits::DataType< ::examples::OddEvenCheck >
template<>
struct DataType< ::examples::OddEvenCheckRequest>
{
  static const char* value()
  {
    return DataType< ::examples::OddEvenCheck >::value();
  }
  static const char* value(const ::examples::OddEvenCheckRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::examples::OddEvenCheckResponse> should match
// service_traits::MD5Sum< ::examples::OddEvenCheck >
template<>
struct MD5Sum< ::examples::OddEvenCheckResponse>
{
  static const char* value()
  {
    return MD5Sum< ::examples::OddEvenCheck >::value();
  }
  static const char* value(const ::examples::OddEvenCheckResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::examples::OddEvenCheckResponse> should match
// service_traits::DataType< ::examples::OddEvenCheck >
template<>
struct DataType< ::examples::OddEvenCheckResponse>
{
  static const char* value()
  {
    return DataType< ::examples::OddEvenCheck >::value();
  }
  static const char* value(const ::examples::OddEvenCheckResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXAMPLES_MESSAGE_ODDEVENCHECK_H
